# This file was generated by GoReleaser. DO NOT EDIT.
cask "yad" do
  version "1.7.0"

  on_macos do
    on_arm do
      sha256 "706f3f5a651db4ab95e4cefc82162ade2fee34859bfd64e437949c0feb626a71"
      url "https://github.com/ilyabrin/yad/releases/download/v#{version}/yad-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "d1d18e75f6133229776d342d49ab6eeea44640ca3e1bb0ef7df66f800957d9d5"
      url "https://github.com/ilyabrin/yad/releases/download/v#{version}/yad-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ea9737997c9d25b7f1b21407d0bf2b26ddafd48f248905580e45b2db53ae313a"
      url "https://github.com/ilyabrin/yad/releases/download/v#{version}/yad-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "9c166aabe6797fc75186b35c3bf489348be62600488e193ca646d176b2688d6c"
      url "https://github.com/ilyabrin/yad/releases/download/v#{version}/yad-#{version}-linux-amd64.tar.gz"
    end
  end

  name "yad"
  desc "Your Yandex.Disk in the terminal"
  homepage "https://github.com/ilyabrin/yad"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yad"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yad"]
    end
  end

  # No zap stanza required
end
