# This file was generated by GoReleaser. DO NOT EDIT.
cask "yad" do
  version "1.7.1"

  on_macos do
    on_arm do
      sha256 "9978f0808e6cc16874b5b44e5aff4154248fe18b22294726457ab421d1bd53de"
      url "https://github.com/ilyabrin/yad/releases/download/v#{version}/yad-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "f13d68a773687f64c366946c95b5de373278484b06643845e9f880bd3eceaffc"
      url "https://github.com/ilyabrin/yad/releases/download/v#{version}/yad-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "39646dd7896977c4f0a8100735043b26b51589331e85a79521c746b2bd11a173"
      url "https://github.com/ilyabrin/yad/releases/download/v#{version}/yad-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "9f2848f3bfc732b1287e31f8b86fef2434e52a651f35b20c8498b6e6e9feaecd"
      url "https://github.com/ilyabrin/yad/releases/download/v#{version}/yad-#{version}-linux-amd64.tar.gz"
    end
  end

  name "yad"
  desc "Your Yandex.Disk in the terminal"
  homepage "https://github.com/ilyabrin/yad"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yad"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yad"]
    end
  end

  # No zap stanza required
end
