# This file was generated by GoReleaser. DO NOT EDIT.
cask "yad" do
  version "1.9.0"

  on_macos do
    on_arm do
      sha256 "60a99150dad83452b17d9c48597dfed42ed222257947120227c592b515598de0"
      url "https://github.com/ilyabrin/yad/releases/download/v#{version}/yad-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "64b0716c668b87b6cc261c6e013e54d6f6c17261b89e734d175f0fd774d64ce3"
      url "https://github.com/ilyabrin/yad/releases/download/v#{version}/yad-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9a78c3b99bc6c85d35ce7d202eab3039a32ca1e2dbfb3b9e223677f9c90cc111"
      url "https://github.com/ilyabrin/yad/releases/download/v#{version}/yad-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "86f40a4c1881227dd7730ac62a0382a06a2ed87033c8ae69c89d66fa00a97e9d"
      url "https://github.com/ilyabrin/yad/releases/download/v#{version}/yad-#{version}-linux-amd64.tar.gz"
    end
  end

  name "yad"
  desc "Your Yandex.Disk in the terminal"
  homepage "https://github.com/ilyabrin/yad"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yad"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yad"]
    end
  end

  # No zap stanza required
end
